version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_book_store_page
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookstore2
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    network_mode: host
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: